# .github/workflows/python-ci.yml

# Name of the workflow as it appears in the GitHub Actions tab
name: Python CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]  # Run on pushes to the main branch
  pull_request:
    branches: [ "main" ]  # Run on pull requests targeting the main branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" (you can name it "test" too)
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # Use the latest Ubuntu virtual machine provided by GitHub

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4 # Use the standard checkout action (v4 is recent)

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4 # Use the standard Python setup action
        with:
          python-version: '3.10' # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: | # Use the shell runner to execute commands
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests with pytest
      - name: Run tests
        run: |
          pytest # Simply run pytest, it will automatically find test_*.py files